from databricks import sql
import os
from dotenv import load_dotenv
import logging
import time
import json

import pandas as pd

logging.getLogger("databricks.sql").setLevel(logging.WARNING)
load_dotenv()

connection = sql.connect(
    server_hostname=os.getenv("SERVER_HOSTNAME"),
    http_path=os.getenv("HTTP_PATH"),
    access_token=os.getenv("ACCESS_TOKEN")
)
cursor = connection.cursor()

create_cursor = connection.cursor()
create_cursor.execute("CREATE SCHEMA IF NOT EXISTS workspace.my_project")
create_cursor.close()

output_catalog = "workspace"   
output_schema = "default"    
output_table = f"{output_catalog}.{output_schema}.facilities_consolidated"

catalog = "databricks_virtue_foundation_dataset_dais_2026"
schema = "virtue_foundation_dataset"
table = "facilities"
table_path = f"{catalog}.{schema}.{table}"

# The validated prompt, split at the 6 points where dynamic column values get inserted.
# Content is IDENTICAL to the Python-validated CONSOLIDATION_PROMPT — just chopped up
# so SQL CONCAT can interleave literal text with column references.

PROMPT_PART_1 = """
ROLE
You are consolidating already-extracted facts about a healthcare facility. The input lists below were generated by running an extraction pipeline separately across MULTIPLE web sources for the same facility, so they contain duplicate, near-duplicate, and sometimes contradictory claims. Your task is to merge and clean them into a single consolidated set — NOT to extract new facts from raw text.

Target Facility: """

PROMPT_PART_2 = """

CATEGORY DEFINITIONS (these were the original extraction categories — use them to keep items in the correct bucket, and to move any misclassified items to the correct one)

- procedure: Clinical procedures, surgical operations, and medical interventions performed at the facility. Specific medical procedures/treatments, surgical services, diagnostic procedures and screenings.

- equipment: Physical medical devices, diagnostic machines, infrastructure, and utilities. Imaging equipment (MRI/CT/X-ray), surgical/OR technology, infrastructure (beds, rooms, buildings, utilities), lab equipment. EXCLUDE generic/universal items that would apply to virtually any clinic (e.g. stethoscopes, thermometers, exam tables, basic furniture) — only include equipment that is specific, distinctive, or notable. CRITICAL: only include a brand name, model number, or specific technical configuration (e.g. "Allegretto IQ 400 laser system", "Philips multi-para monitors", "laminar airflow OT") if that EXACT brand/model/configuration is explicitly present in the raw equipment input. Do NOT infer, guess, or add plausible-sounding equipment details based on the facility's type or specialty. If the raw equipment claim is generic (e.g. "has a laser system" with no brand/model given), keep the claim generic — do not embellish it with invented specifics.

- capability: Medical capabilities defining what level and types of clinical care the facility can deliver. Trauma/emergency levels, specialized units (ICU/NICU/burn unit), clinical programs, diagnostic capabilities, accreditations, care setting (inpatient/outpatient), staffing levels, patient capacity. EXCLUDES: addresses, contact info, business hours, pricing, founding year, doctor headcounts, or other organizational facts not related to clinical care delivery — put those in facility_facts instead. ALSO EXCLUDE directory/ranking/SEO listing mentions (e.g. "listed among top hospitals on Practo", "ranked as a top clinic", "featured on [directory site]") — these are marketing/listing artifacts, not clinical capabilities, and should be discarded entirely (not moved to another category).

- facility_facts: Non-clinical organizational facts ONLY — founding year, staff/doctor counts, ownership details, named staff members, locations mentioned, accreditations of the organization itself (not clinical accreditations, which belong in capability). This is NOT a place to restate or paraphrase what services/procedures/capabilities the facility offers — that information belongs in procedures/capabilities/equipment or is already captured in the description. If no genuine organizational facts (of the specific type described above) are present in the input, return an empty list. Do NOT invent a fact by rephrasing the description or service list just to avoid an empty list.

INPUT DATA FOR THIS FACILITY

Description: """

PROMPT_PART_3 = """

Raw capability claims (from multiple sources, may duplicate/conflict): """

PROMPT_PART_4 = """

Raw procedure claims (from multiple sources, may duplicate): """

PROMPT_PART_5 = """

Raw equipment claims (from multiple sources, often sparse/low-confidence): """

PROMPT_PART_6 = """

Specialty tags (from multiple sources, likely duplicated): """

PROMPT_PART_7 = """

INSTRUCTIONS

1. For capability, procedure, and equipment: merge near-duplicate or overlapping claims into ONE clean claim each, using the clearest/most specific wording available FROM THE INPUT ONLY. For each merged claim, include the EXACT original string(s) from the input list that support it, copied verbatim, as "evidence".

2. Re-sort any misclassified items into their correct category per the definitions above. Directory/ranking/listing mentions should be discarded entirely, not moved anywhere.

3. equipment: if the raw list is empty, or contains only vague/non-specific mentions, or contains only generic/universal items, return an empty list. NEVER add a brand name, model number, or technical specification that is not verbatim present in the raw equipment input.

4. specialties: deduplicate the tags exactly as given, preserving original casing/spelling. Do not rename or reinterpret them.

5. facility_facts: extract ONLY genuine non-clinical organizational facts explicitly stated in the capability list, procedure list, or description. Do not restate services/procedures as "facts." If none exist, return an empty list.

6. data_quality.has_rich_description: true if the description is genuine descriptive prose.

7. data_quality.conflicting_claims: list any claims that directly contradict each other. IMPORTANT: if a fact is contradictory, it belongs ONLY here — do not also list the contradictory versions as separate entries elsewhere. Empty list if no conflicts.

8. data_quality.possible_merged_facility: set to true if the input data appears to describe TWO OR MORE DISTINCT physical facilities merged into one record. Set to false otherwise. When true, briefly note why in data_quality.merge_suspicion_reason.

CRITICAL RULES
- Every "evidence" string must be an EXACT verbatim substring from the corresponding input list — never paraphrase or invent evidence.
- Do not fabricate facts not present in the input data, especially equipment brand names, model numbers, and technical specifications.
- Discard directory/ranking/SEO listing mentions entirely.
- Empty categories are fine and expected — do not force content into a category to avoid an empty list.
- Any single contradictory fact appears ONCE, inside conflicting_claims — never duplicated elsewhere.
- Ensure valid JSON syntax: escape any double-quote characters that appear within string values using \\"
- Output ONLY valid JSON matching the schema below. No markdown, no preamble.

OUTPUT SCHEMA
{
  "capabilities": [{"claim": "string", "evidence": ["string"]}],
  "procedures": [{"claim": "string", "evidence": ["string"]}],
  "equipment": [{"claim": "string", "evidence": ["string"]}],
  "specialties": ["string"],
  "facility_facts": [{"fact": "string", "evidence": ["string"]}],
  "data_quality": {
    "has_rich_description": true,
    "conflicting_claims": ["string"],
    "possible_merged_facility": false,
    "merge_suspicion_reason": "string or null"
  }
}
"""

def sql_escape(s):
    """Escape single quotes for embedding as a SQL string literal."""
    return s.replace("'", "''")

concat_expr = f"""CONCAT(
  '{sql_escape(PROMPT_PART_1)}', COALESCE(name, ''),
  '{sql_escape(PROMPT_PART_2)}', COALESCE(description, '(no description)'),
  '{sql_escape(PROMPT_PART_3)}', COALESCE(capability, '[]'),
  '{sql_escape(PROMPT_PART_4)}', COALESCE(procedure, '[]'),
  '{sql_escape(PROMPT_PART_5)}', COALESCE(equipment, '[]'),
  '{sql_escape(PROMPT_PART_6)}', COALESCE(specialties, '[]'),
  '{sql_escape(PROMPT_PART_7)}'
)"""

query = f"""
CREATE OR REPLACE TABLE {output_table} AS
SELECT
  unique_id,
  name,
  ai_query('databricks-meta-llama-3-3-70b-instruct', {concat_expr}) AS consolidated_json
FROM {table_path}
"""

print("Running full-table ai_query consolidation... this may take a while for 10k rows.")
start = time.time()
cursor.execute(query)
print(f"Done in {time.time() - start:.1f}s. Table created: {output_table}")

cursor.execute(f"SELECT COUNT(*) FROM {output_table}")
print(f"Row count: {cursor.fetchone()[0]}")

def parse_llm_output(raw_output):
    if raw_output is None:
        return None
    cleaned = raw_output.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("```")[1]
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
    try:
        return json.loads(cleaned.strip())
    except json.JSONDecodeError:
        return None

results_cursor = connection.cursor()
results_cursor.execute(f"SELECT unique_id, name, consolidated_json FROM {output_table}")
columns = [desc[0] for desc in results_cursor.description]
results_df = pd.DataFrame(results_cursor.fetchall(), columns=columns)

results_df["parsed"] = results_df["consolidated_json"].apply(parse_llm_output)
failed_mask = results_df["parsed"].isna()

print(f"Total rows: {len(results_df)}")
print(f"Failed to parse: {failed_mask.sum()}")

failed_ids = results_df.loc[failed_mask, "unique_id"].tolist()

results_cursor.close()
cursor.close()
connection.close()